config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  resources :books

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
    redirect_to root_path
    
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    redirect_to root_path
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title,:body)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>
<div>
    <%= form_with model:@book,url:book_path,local:true do |f| %>
        <div>
            <%= f.label :title %>
            <%= f.text_field :title %>
        </div>
        <div>
            <%= f.label :body %>
            <%= f.text_field :body %>
        </div>
        <div>
            <%= f.submit '保存' %>
        </div>
    <% end %>
</div>

app/views/books/index.html.erb
<h1>Books#index</h1>
<p>Find me in app/views/books/index.html.erb</p>
<% @books.each do |book| %>
    <div><%= book.user.id %></div>
    <div><%= book.user.email %></div>
    <div><%= book.id %></div>
    <div><%= book.title %></div>
    <div><%= book.body %></div>
    <div><%= link_to '詳細へ', book_path(book.id) %></div>
    <div><%= link_to '削除', book_path(book.id), method: :delete %></div>
<% end %>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>
<%= form_with model:@book,url:books_path, local:true do |f| %>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <div>
        <%= f.label :body %>
        <%= f.text_area :body %>
    </div>
    <div>
        <%= f.submit '保存' %>
    </div>
    
<% end %>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>
<%= @book.title %>
<%= @book.body %>
<%= link_to '編集', edit_book_path(@book.id) %>
<%= link_to '戻る', books_path %>

app/views/homes/top.html.erb
<div>
    <h1><strong>トップ画面</strong>へようこそ</h1>
    <h2>学習内容復習</h2>
    <p>こんにちはこんばんは！</p>
    
    <%= link_to '一覧', books_path %>
    <%= link_to '新規投稿', new_book_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Running3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--コメント-->
    <ol>
      <% if user_signed_in? %>
        <li>
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to 'ログイン', new_user_session_path %>
        </li>
        <li>
          <%= link_to '新規投稿', new_user_registration_path %>
        </li>
      <% end %>
    </ol>
    <%= yield %>
  </body>
</html>